// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoadManagerPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Page(true).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>LogIn</title><script src=\"https://unpkg.com/htmx.org@1.9.2\"></script></head><body><form hx-post=\"/products/action/redirect\"><div class=\"form-group\"><label for=\"product\">product Id </label><br><input type=\"text\" id=\"product\" name=\"product\" required><br><input type=\"radio\" id=\"delete\" name=\"action\" value=\"delete\" required> <label for=\"delete\">Delete Product</label><br><input type=\"radio\" id=\"modify\" name=\"action\" value=\"modify\" required> <label for=\"modify\">modify Product</label><br></div><button>Submit action </button></form><form hx-post=\"/products/action/redirect\"><div class=\"form-group\"><input type=\"radio\" id=\"AddAccessory\" name=\"addproduct\" value=\"AddAccessory\" required> <label for=\"AddAccessory\">Add Accessory</label><br><input type=\"radio\" id=\"AddBicycle\" name=\"addproduct\" value=\"AddBicycle\" required> <label for=\"AddBicycle\">Add Bicycle</label><br></div><button>Submit action </button></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
